artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras
  updated_base_model_path: artifacts/base_model/base_model_updated.keras

callbacks:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callbacks/chcekpoint_dir/model.keras

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras

evaluation:
  root_dir: artifacts/evaluation